Move towards oilshell

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -1,11 +1,19 @@
-#!/usr/bin/env bash
-# This pre-commit hook looks for `fdescribe`, `fcontext`, `fit`, `fspecify` and `fexample` in the
-# staged files and exits with an error code of 1 if there are such changes.
+#!/usr/bin/env osh
+shopt --set oil:basic
 
-if [ "$(echo $(uname -s) | cut -c 1-6)" == "Darwin" ]; then
-    . $HOME/dotfiles/git/hooks/pre-commit.bash
-elif [ "$(echo $(uname -s) | cut -c 1-5)" == "Linux" ]; then
-    . $HOME/dotfiles/git/hooks/pre-commit.bash
+if [ "$(echo $(uname -s) | cut -c 1-6)" == "Darwin" ] || [ "$(echo $(uname -s) | cut -c 1-5)" == "Linux" ]; then
+    local hook_status=0
+    for f in $HOME/dotfiles/git/hooks/pre-commits/*.bash; do
+        local result=$(osh $f)
+        if [ -n "$result" ]; then
+            echo $result
+            hook_status=1
+        fi
+    done
+    if [[ $hook_status -ne 0 ]]; then
+        echo -e "\nHook failed, commit aborted"
+        exit 1
+    fi
 elif [ "$(echo $(uname -s) | cut -c 1-10)" == "MINGW32_NT" ]; then
     exec powershell.exe -NoProfile -ExecutionPolicy Bypass -File $HOME/dotfiles/git/hooks/pre-commit.ps1
 elif [ "$(echo $(uname -s) | cut -c 1-10)" == "MINGW64_NT" ]; then
